#!/bin/bash -x

# Request a follow from the target
IFS=""
hostname=$(cat config/hostname):$(cat config/port)
key=$(curl -s ${1}/follow?url=http://${hostname})

. scripts/functions

gpg=$(findGPG)

if ! grep ${1} data/following 2> /dev/null; then
    email=$(echo $key \
                | $gpg --with-colons 2> /dev/null \
                | grep ^uid \
                | cut -d '<' -f 2 \
                | tr -d '>:')
    keyid=$(echo $key \
                | $gpg --with-colons --with-fingerprint 2> /dev/null \
                | grep -E "^fpr"\
                | tr -d 'fpr:::::::::');

    if [[ ${email} != "" && ${keyid} != "" ]]; then
        echo ${email} ${1} ${keyid} >> data/following
        exit 0
    else
        echo "Error adding following for ${1}"
        exit 1
    fi
else
    echo "Already following ${1}"
    exit 1
fi


