#!/bin/bash
# Return a key ID given an email address.

[ -z "$1" ] && echo "./getkey email@address" && exit 1

. functions
gpg=$(findGPG)

$gpg --with-colons --with-fingerprint --list-keys $1 2> /dev/null \
    | grep -E "^fpr" \
    | head -1 \
    | cut -d ":" -f 10 \
    | tr -d ' '
